pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    triggers {
        cron 'H H/6 * * *'
    }

    stages {
        stage('checkout') {
            steps {
                echo 'checkout HL Immix branch'
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: '*/feature/gc']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [[url: 'https://github.com/Aurel300/hashlink.git']]
                ])                
            }
        }

        stage('compile') {
            steps {
                echo 'compile HL Immix branch'
                sh '''
                PREFIX=/home/tooling/hashlink/hashlink-immix make
                '''
            }
        }

        stage('install') {
            steps {
                echo 'install HL Immix branch'
                sh '''
                PREFIX=/home/tooling/hashlink/hashlink-immix make install
                '''
            }
        }
    }
}
