pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
    }
    triggers {
        cron 'H H/6 * * *'
    }

    stages {
        stage('build hxcpp for Haxe nightly') {
            steps {
                echo 'build hxcpp for Haxe nightly'
                sh '''
                    mkdir -p $TOOLING_BASE/hxcpp/hxcppHaxeNightly
                    cd $TOOLING_BASE/hxcpp/hxcppHaxeNightly
                    # git clone https://github.com/HaxeFoundation/hxcpp.git .
                    git checkout -- .
                    git pull
                    rm -rf bin project/cppia_bin
                    lix scope create
                    lix install haxe nightly
                    (cd tools/hxcpp; haxe compile.hxml)

                    cd project 
                    lix scope create
                    lix install haxe nightly
                    lix dev hxcpp ..
                    haxelib dev hxcpp ..
                    echo "y" | haxe compile-cppia.hxml
                '''
            }
        }
    
        stage('build hxcpp for Haxe 4') {
            steps {
                echo 'build hxcpp for Haxe 4'
                sh '''
                    mkdir -p $TOOLING_BASE/hxcpp/hxcppHaxe4
                    cd $TOOLING_BASE/hxcpp/hxcppHaxe4
                    # git clone https://github.com/HaxeFoundation/hxcpp.git .
                    git checkout -- .
                    git pull
                    rm -rf bin project/cppia_bin
                    lix scope create
                    lix install haxe 4.3.7
                    (cd tools/hxcpp; haxe compile.hxml)

                    cd project 
                    lix scope create
                    lix install haxe 4.3.7
                    lix dev hxcpp ..
                    haxelib dev hxcpp ..
                    echo "y" | haxe compile-cppia.hxml
                '''
            }
        }

        stage('build hxcpp for Haxe 5') {
            steps {
                echo 'build hxcpp for Haxe 5'
                sh '''
                    mkdir -p $TOOLING_BASE/hxcpp/hxcppHaxe5
                    cd $TOOLING_BASE/hxcpp/hxcppHaxe5
                    # git clone https://github.com/HaxeFoundation/hxcpp.git .
                    git checkout -- .
                    git pull
                    rm -rf bin project/cppia_bin
                    lix scope create
                    lix install haxe 5.0.0-preview.1
                    (cd tools/hxcpp; haxe compile.hxml)

                    cd project 
                    lix scope create
                    lix install haxe 5.0.0-preview.1
                    lix dev hxcpp ..
                    haxelib dev hxcpp ..
                    echo "y" | haxe compile-cppia.hxml
                '''
            }
        }

        stage('build hxcpp for Haxe 3') {
            steps {
                echo 'build hxcpp for Haxe 3'
                sh '''
                    mkdir -p $TOOLING_BASE/hxcpp/hxcppHaxe3
                    cd $TOOLING_BASE/hxcpp/hxcppHaxe3
                    # git clone https://github.com/HaxeFoundation/hxcpp.git .
                    git checkout -- .
                    git pull
                    rm -rf bin project/cppia_bin
                    lix scope create
                    lix install haxe 4.3.3
                    (cd tools/hxcpp; haxe compile.hxml)

                    cd project 
                    lix scope create
                    lix install haxe 3.4.7
                    lix dev hxcpp ..
                    haxelib dev hxcpp ..
                    echo "y" | haxe compile-cppia.hxml
                '''
            }
        }
    }
}
